<?php
/***************************************************************************
   -------------------
   This file has been generated by HyperDev in 2011-02-28 11:30:09.
   HyperDev is a GNU code generator developed by Ruben Dorado. 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License           *
 *   version 2.1 as published by the Free Software Foundation;             *
 *                                                                         *
 ***************************************************************************/
*/
?>
<?php include_once("dao/roleDAO.php")?>
<?php
  $result = role_find_all();
?>

<table border="1" style="border-collapse:collapse;">
 <tr>
  <th>name</th>
  <th>id</th>
  <th>Options</th>
 </tr>
 <?php
    $len = count($result);
   for($i=0;$i<$len;$i++){ ?>
      <tr>         
       <td><?php echo $result[$i]->get_name(); ?></td>
       <td><?php echo $result[$i]->get_id(); ?></td>
       <td>
        <a href="role_edit.php?id=<?=$result[$i]->_get_id()?>">Edit</a>
        <a href="role_do_delete.php?id=<?=$result[$i]->_get_id()?>">Delete</a>
        <a href="role_details.php?id=<?=$result[$i]->_get_id()?>">Details</a>  
       </td>    
      </tr>
<?php }
 ?>
</table>
<br/>
<a href="role_insert.php">New</a>