<?php
/***************************************************************************
   -------------------
   This file has been generated by HyperDev in 2011-02-28 11:30:09.
   HyperDev is a GNU code generator developed by Ruben Dorado. 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License           *
 *   version 2.1 as published by the Free Software Foundation;             *
 *                                                                         *
 ***************************************************************************/
*/
?>
<?php include_once("dao/userDAO.php")?>
<?php
  $result = user_find_all();
?>

<table border="1" style="border-collapse:collapse;">
 <tr>
  <th>user_id</th>
  <th>name</th>
  <th>login</th>
  <th>email</th>
  <th>passwrd</th>
  <th>role</th>
  <th>Options</th>
 </tr>
 <?php
    $len = count($result);
   for($i=0;$i<$len;$i++){ ?>
      <tr>         
       <td><?php echo $result[$i]->get_user_id(); ?></td>
       <td><?php echo $result[$i]->get_name(); ?></td>
       <td><?php echo $result[$i]->get_login(); ?></td>
       <td><?php echo $result[$i]->get_email(); ?></td>
       <td><?php echo $result[$i]->get_passwrd(); ?></td>
       <td><?php echo $result[$i]->get_role(); ?></td>
       <td>
        <a href="user_edit.php?id=<?=$result[$i]->_get_id()?>">Edit</a>
        <a href="user_do_delete.php?id=<?=$result[$i]->_get_id()?>">Delete</a>
        <a href="user_details.php?id=<?=$result[$i]->_get_id()?>">Details</a>  
       </td>    
      </tr>
<?php }
 ?>
</table>
<br/>
<a href="user_insert.php">New</a>